import { FormEvent, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import type { College } from "../types";

export default function PrincipalDashboardPage() {
  const navigate = useNavigate(); const [college, setCollege] = useState<College | null>(null); const [message, setMessage] = useState(""); const token = sessionStorage.getItem("principal-session");
  useEffect(() => { if (!token) { navigate("/principal-login"); return; } fetch("/api/college").then((response) => response.json()).then(setCollege); }, [navigate, token]);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!college) return; const response = await fetch("/api/admin/college", { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(college) }); setMessage(response.ok ? "Changes saved. The public website is updated." : "Changes could not be saved. Please sign in again."); };
  if (!college) return <main className="admin-page"><p>Loading portal…</p></main>;
  return <main className="admin-page"><section className="admin-card dashboard-card"><div className="admin-heading"><div><p className="section-label">Principal portal</p><h1>Website updates</h1></div><Link className="detail-back" to="/">View website</Link></div><p>Update the information below. Changes are saved by the college backend.</p><form onSubmit={save}><label>College summary<textarea value={college.summary} onChange={(event) => setCollege({ ...college, summary: event.target.value })} /></label><h2>Courses</h2>{college.courses.map((course, index) => <div className="admin-row" key={course.route}><label>Course<input value={course.title} onChange={(event) => { const courses = [...college.courses]; courses[index] = { ...course, title: event.target.value }; setCollege({ ...college, courses }); }} /></label><label>Annual fee<input value={course.fees} onChange={(event) => { const courses = [...college.courses]; courses[index] = { ...course, fees: event.target.value }; setCollege({ ...college, courses }); }} /></label></div>)}<h2>Faculty</h2>{college.faculty.map((person, index) => <div className="admin-row" key={`${person.name}-${index}`}><label>Name<input value={person.name} onChange={(event) => { const faculty = [...college.faculty]; faculty[index] = { ...person, name: event.target.value }; setCollege({ ...college, faculty }); }} /></label><label>Role / department<input value={person.role} onChange={(event) => { const faculty = [...college.faculty]; faculty[index] = { ...person, role: event.target.value }; setCollege({ ...college, faculty }); }} /></label></div>)}<button className="admin-add" type="button" onClick={() => setCollege({ ...college, faculty: [...college.faculty, { name: "New lecturer", role: "Lecturer - Department" }] })}>+ Add lecturer</button><button className="button primary">Save changes</button>{message && <p className="form-message">{message}</p>}</form></section></main>;
}
